version: '3.8'

services:
  urlshort:
    build: ./
    command: ./urlshort
    ports:
      - 50001:50001
    depends_on:
      - db
    environment:
      #- DB_URL="user=postgres password=postgres host=db port=5432 dbname=url"
      - DB_URL=postgres://postgres:postgres@db:5432/url
      - DB_PASSWORD=postgres
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: url
    ports:
      - 5432:5432